export * as authController from "./auth";
export * as heroController from "./hero";
export * as categoryController from "./category";
export * as courseController from "./course";
export * as aboutUsController from "./about-us";
export * as faqController from "./faq";
export * as privacyPolicyController from "./privacy-policy";
export * as termsConditionController from "./terms-condition";
export * as blogController from "./blog";
